services:
  fraud_url:
    image: python:3.12.8
    container_name: realtime_fraud_visitors
    ports:
      - "8648:8648"
    volumes:
      - /data01/lixin/realtime_fraud_visitors:/data/app

    entrypoint: ["/bin/sh", "-c"]
    command: ["sleep infinity"]
    privileged: true
    shm_size: '10g'